#!/usr/bin/env bash
# Configures nginx with an X-Served-By header using the server hostname

# shellcheck disable=SC2154

apt-get update -y
apt-get install -y nginx

echo 'Holberton School for the win!' > /var/www/html/index.html

cat > /etc/nginx/sites-available/default <<'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
        add_header X-Served-By $hostname;
    }
}
EOF

nginx -t
service nginx restart
