#!/usr/bin/env bash
# Installs and configures HAProxy to load balance between two web servers

set -e

apt-get update -y
apt-get install -y haproxy

sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

cat > /etc/haproxy/haproxy.cfg <<'EOF'
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 32.192.227.92:80 check
    server web-02 3.87.14.177:80 check
EOF

haproxy -f /etc/haproxy/haproxy.cfg -c
service haproxy restart
